In [1]:
import pandas as pd
from datetime import datetime
pd.set_option('display.max_columns', None)

_EXTRACTED_META_COLS = ["_filter_param", "_filter_value", "_extract_datetime"]

def _add_openalex_extracted_metadata(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    for col in _EXTRACTED_META_COLS:
        if col not in df.columns:
            df[col] = pd.NA
    return df

def _add_openalex_loaded_metadata(df: pd.DataFrame, load_datetime=None) -> pd.DataFrame:
    df = df.copy()
    if load_datetime is None:
        load_datetime = datetime.today()
    df["_load_datetime"] = pd.to_datetime(load_datetime)
    return df

In [2]:
df_author_raw = catalog.load('raw/openalex/author#parquet')
df_author_raw

[03/04/26 12:34:24] INFO     Loading data from raw/openalex/author#parquet (ParquetDataset)... ]8;id=399731;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=362454;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

,id,orcid,display_name,display_name_alternatives,works_count,cited_by_count,summary_stats,ids,affiliations,last_known_institutions,topics,topic_share,x_concepts,counts_by_year,longest_name,parsed_longest_name,block_key,works_api_url,updated_date,created_date,_filter_param,_filter_value,_extract_datetime
0,https://openalex.org/A5100630207,https://orcid.org/0000-0002-2770-9031,M. Weber,"[A Shalmani, A. F. Webb, A. T. Waugh, A. Warbu...",3820,258783,"{'2yr_mean_citedness': 3.8990825688073394, 'h_...",{'openalex': 'https://openalex.org/A5100630207...,"[{'institution': {'country_code': 'US', 'displ...",None,"[{'count': 2935, 'display_name': 'Particle phy...",[{'display_name': 'High-Energy Particle Collis...,"[{'display_name': 'Physics', 'id': '121332964'...","[{'cited_by_count': 0, 'oa_works_count': 0, 'w...",A. Washbrook,"{'first': 'a', 'last': 'washbrook', 'middle': ...",a washbrook,https://api.openalex.org/works?filter=author.i...,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03
1,https://openalex.org/A5006906048,https://orcid.org/0000-0002-5211-2536,Stefan R. Bornstein,"[Boerwinkle, Eric, Bornstein, S.R., Bornstein,...",3157,73662,"{'2yr_mean_citedness': 13.353535353535353, 'h_...",{'openalex': 'https://openalex.org/A5006906048...,"[{'institution': {'country_code': 'IT', 'displ...","[{'country_code': 'GB', 'display_name': 'King'...","[{'count': 186, 'display_name': 'Hormonal Regu...",[{'display_name': 'Adrenal Hormones and Disord...,"[{'display_name': 'Medicine', 'id': '71924100'...","[{'cited_by_count': 181, 'oa_works_count': 0, ...",Folkert W. Asselbergs,"{'first': 'folkert', 'last': 'asselbergs', 'mi...",f asselbergs,https://api.openalex.org/works?filter=author.i...,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03
2,https://openalex.org/A5061649047,https://orcid.org/0000-0002-2696-7266,Klaus A. Miczek,"[K A MICZEK, K A Miczek, K MICZEK, K. A. Micze...",3088,23212,"{'2yr_mean_citedness': 37.5, 'h_index': 83, 'i...",{'openalex': 'https://openalex.org/A5061649047...,"[{'institution': {'country_code': 'US', 'displ...","[{'country_code': 'US', 'display_name': 'Tufts...","[{'count': 201, 'display_name': 'Neurotransmit...",[{'display_name': 'Neurotransmitter Receptor I...,"[{'display_name': 'Neuroscience', 'id': '16976...","[{'cited_by_count': 57, 'oa_works_count': 1, '...",Klaus A. Miczek,"{'first': 'klaus', 'last': 'miczek', 'middle':...",k miczek,https://api.openalex.org/works?filter=author.i...,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03
3,https://openalex.org/A5087325828,None,F. Barreiro,"[A. Baroncelli, A. J. Barr, A.J. Barr, A. A. K...",2901,182926,"{'2yr_mean_citedness': 5.157377049180328, 'h_i...",{'openalex': 'https://openalex.org/A5087325828...,"[{'institution': {'country_code': 'US', 'displ...",None,"[{'count': 1932, 'display_name': 'Particle phy...",[{'display_name': 'High-Energy Particle Collis...,"[{'display_name': 'Physics', 'id': '121332964'...","[{'cited_by_count': 2, 'oa_works_count': 0, 'w...","Assamagan, Ketevi Adikle","{'first': 'ketevi', 'last': 'assamagan', 'midd...",k assamagan,https://api.openalex.org/works?filter=author.i...,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03
4,https://openalex.org/A5107465601,https://orcid.org/0000-0001-9500-2487,B. Trocmé,"[A. Traeet, A. Tricoli, A. Trivedi, Aaltonen, ...",2808,190253,"{'2yr_mean_citedness': 5.295, 'h_index': 183, ...",{'openalex': 'https://openalex.org/A5107465601...,"[{'institution': {'country_code': 'FR', 'displ...","[{'country_code': 'FR', 'display_name': 'Insti...","[{'count': 1717, 'display_name': 'Particle phy...",[{'display_name': 'High-Energy Particle Collis...,"[{'display_name': 'Physics', 'id': '121332964'...","[{'cited_by_count': 0, 'oa_works_count': 1, 'w...","Aaltonen, T.","{'first': 't', 'last': 'aaltonen', 'middle': '...",t aaltonen,https://api.openalex.org/works?filter=author.i...,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,https://openalex.org/A5107346850,https://orcid.org/0000-0002-2637-4778,H. Schieler,"[B. R. Dawson, C. Raab, Cantu, D. Rysewyk, H B...",810,16272,"{'2yr_mean_citedness': 2.046511627906977, 'h_i...",{'openalex': 'https://openalex.org/A5107346850...,"[{'institution': {'country_code': 'DE', 'displ...","[{'country_code': 'BE', 'display_name': 'UCLou...","[{'count': 683, 'display_name': 'Astrophysics ...","[{'display_name': 'Neutrino Physics Research',...","[{'display_name': 'Physics', 'id': '121332964'...","[{'cited_by_count': 0, 'oa_works_count': 0, 'w...","Cantu, D. Rysewyk","{'first': 'd', 'last': 'cantu', 'middle': 'rys...",d cantu,https://api.openalex.org/works?filter=author.i...,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03
196,https://openalex.org/A5072713248,https://orcid.org/0000-0002-8154-6958,D. R. Napoli,"[A. Dewald, A. Gadea, D Napoli, D R Napoli, D ...",809,11474,"{'2yr_mean_citedness': 0.64, 'h_index': 46, 'i...",{'openalex': 'https://openalex.org/A5072713248...,"[{'institution': {'country_code': 'IT', 'displ...","[{'country_code': 'IT', 'display_name': 'Istit...","[{'count': 661, 'display_name': 'Nuclear physi...",[{'display_name': 'Astronomical and nuclear sc...,"[{'display_name': 'Physics', 'id': '121332964'...","[{'cited_by_count': 13, 'oa_works_count': 0, '...",D R Napoli for the Clara-Prisma collaboration,"{'first': 'd', 'last': 'collaboration', 'middl...",d collaboration,https://api.openalex.org/works?filter=author.i...,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03
197,https://openalex.org/A5076510192,https://orcid.org/0000-0003-0991-4434,Anthony Herrel,"[A HERREL, A Herrel, A. HERREL, A. Herrel, A. ...",808,23232,"{'2yr_mean_citedness': 1.8194444444444444, 'h_...",{'openalex': 'https://openalex.org/A5076510192...,"[{'institution': {'country_code': 'FR', 'displ...","[{'country_code': 'BE', 'display_name': 'Unive...","[{'count': 376, 'display_name': 'Amphibian and...",[{'display_name': 'Amphibian and Reptile Biolo...,"[{'display_name': 'Biology', 'id': '86803240',...","[{'cited_by_count': 177, 'oa_works_count': 0, ...","Anthony, Herrel","{'first': 'herrel', 'last': 'anthony', 'middle...",h anthony,https://api.openalex.org/works?filter=author.i...,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03
198,https://openalex.org/A5005945570,https://orcid.org/0000-0003-2711-8458,Teófilo Rojo,"[Adolfo La Rosa-Toro, Armand, M., J. I. Ruiz D...",806,39733,"{'2yr_mean_citedness': 9.333333333333334, 'h_i...",{'openalex': 'https://openalex.org/A5005945570...,"[{'institution': {'country_code': 'ES', 'displ...","[{'country_code': 'ES', 'display_name': 'Unive...","[{'count': 240, 'display_name': 'Advancements ...",[{'display_name': 'Crystal Structures and Prop...,"[{'display_name': 'Chemistry', 'id': '18559268...","[{'cited_by_count': 47, 'oa_works_count': 0, '...",J. I. Ruiz De Larramendi,"{'first': 'j', 'last': 'de larramendi', 'middl...",j de larramendi,https://api.openalex.org/works?filter=author.i...,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03
199,https://openalex.org/A5012273051,None,Francesc Illas,"[F ILLAS, F Illas, F. ILLAS, F. Illas, FRANCES...",805,36063,"{'2yr_mean_citedness': 10.0, 'h_index': 91, 'i...",{'openalex': 'https://openalex.org/A5012273051...,"[{'institution': {'country_code': 'EC', 'displ...","[{'country_code': 'ES', 'display_name': 'Unive...","[{'count': 297, 'display_name': 'Advanced Chem...",[{'display_name': 'Advanced Chemical Physics S...,"[{'display_name': 'Chemistry', 'id': '18559268...","[{'cited_by_count': 20, 'oa_works_count': 0, '...","Illas, Francesc","{'first': 'francesc', 'last': 'illas', 'middle...",f illas,https://api.openalex.org/works?filter=author.i...,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03

# Profiling

In [3]:
df_author_raw.dtypes

id                           object
orcid                        object
display_name                 object
display_name_alternatives    object
works_count                   int64
cited_by_count                int64
summary_stats                object
ids                          object
affiliations                 object
last_known_institutions      object
topics                       object
topic_share                  object
x_concepts                   object
counts_by_year               object
longest_name                 object
parsed_longest_name          object
block_key                    object
works_api_url                object
updated_date                 object
created_date                 object
_filter_param                object
_filter_value                object
_extract_datetime            object
dtype: object

In [4]:
df_author_raw

,id,orcid,display_name,display_name_alternatives,works_count,cited_by_count,summary_stats,ids,affiliations,last_known_institutions,topics,topic_share,x_concepts,counts_by_year,longest_name,parsed_longest_name,block_key,works_api_url,updated_date,created_date,_filter_param,_filter_value,_extract_datetime
0,https://openalex.org/A5100630207,https://orcid.org/0000-0002-2770-9031,M. Weber,"[A Shalmani, A. F. Webb, A. T. Waugh, A. Warbu...",3820,258783,"{'2yr_mean_citedness': 3.8990825688073394, 'h_...",{'openalex': 'https://openalex.org/A5100630207...,"[{'institution': {'country_code': 'US', 'displ...",None,"[{'count': 2935, 'display_name': 'Particle phy...",[{'display_name': 'High-Energy Particle Collis...,"[{'display_name': 'Physics', 'id': '121332964'...","[{'cited_by_count': 0, 'oa_works_count': 0, 'w...",A. Washbrook,"{'first': 'a', 'last': 'washbrook', 'middle': ...",a washbrook,https://api.openalex.org/works?filter=author.i...,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03
1,https://openalex.org/A5006906048,https://orcid.org/0000-0002-5211-2536,Stefan R. Bornstein,"[Boerwinkle, Eric, Bornstein, S.R., Bornstein,...",3157,73662,"{'2yr_mean_citedness': 13.353535353535353, 'h_...",{'openalex': 'https://openalex.org/A5006906048...,"[{'institution': {'country_code': 'IT', 'displ...","[{'country_code': 'GB', 'display_name': 'King'...","[{'count': 186, 'display_name': 'Hormonal Regu...",[{'display_name': 'Adrenal Hormones and Disord...,"[{'display_name': 'Medicine', 'id': '71924100'...","[{'cited_by_count': 181, 'oa_works_count': 0, ...",Folkert W. Asselbergs,"{'first': 'folkert', 'last': 'asselbergs', 'mi...",f asselbergs,https://api.openalex.org/works?filter=author.i...,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03
2,https://openalex.org/A5061649047,https://orcid.org/0000-0002-2696-7266,Klaus A. Miczek,"[K A MICZEK, K A Miczek, K MICZEK, K. A. Micze...",3088,23212,"{'2yr_mean_citedness': 37.5, 'h_index': 83, 'i...",{'openalex': 'https://openalex.org/A5061649047...,"[{'institution': {'country_code': 'US', 'displ...","[{'country_code': 'US', 'display_name': 'Tufts...","[{'count': 201, 'display_name': 'Neurotransmit...",[{'display_name': 'Neurotransmitter Receptor I...,"[{'display_name': 'Neuroscience', 'id': '16976...","[{'cited_by_count': 57, 'oa_works_count': 1, '...",Klaus A. Miczek,"{'first': 'klaus', 'last': 'miczek', 'middle':...",k miczek,https://api.openalex.org/works?filter=author.i...,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03
3,https://openalex.org/A5087325828,None,F. Barreiro,"[A. Baroncelli, A. J. Barr, A.J. Barr, A. A. K...",2901,182926,"{'2yr_mean_citedness': 5.157377049180328, 'h_i...",{'openalex': 'https://openalex.org/A5087325828...,"[{'institution': {'country_code': 'US', 'displ...",None,"[{'count': 1932, 'display_name': 'Particle phy...",[{'display_name': 'High-Energy Particle Collis...,"[{'display_name': 'Physics', 'id': '121332964'...","[{'cited_by_count': 2, 'oa_works_count': 0, 'w...","Assamagan, Ketevi Adikle","{'first': 'ketevi', 'last': 'assamagan', 'midd...",k assamagan,https://api.openalex.org/works?filter=author.i...,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03
4,https://openalex.org/A5107465601,https://orcid.org/0000-0001-9500-2487,B. Trocmé,"[A. Traeet, A. Tricoli, A. Trivedi, Aaltonen, ...",2808,190253,"{'2yr_mean_citedness': 5.295, 'h_index': 183, ...",{'openalex': 'https://openalex.org/A5107465601...,"[{'institution': {'country_code': 'FR', 'displ...","[{'country_code': 'FR', 'display_name': 'Insti...","[{'count': 1717, 'display_name': 'Particle phy...",[{'display_name': 'High-Energy Particle Collis...,"[{'display_name': 'Physics', 'id': '121332964'...","[{'cited_by_count': 0, 'oa_works_count': 1, 'w...","Aaltonen, T.","{'first': 't', 'last': 'aaltonen', 'middle': '...",t aaltonen,https://api.openalex.org/works?filter=author.i...,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,https://openalex.org/A5107346850,https://orcid.org/0000-0002-2637-4778,H. Schieler,"[B. R. Dawson, C. Raab, Cantu, D. Rysewyk, H B...",810,16272,"{'2yr_mean_citedness': 2.046511627906977, 'h_i...",{'openalex': 'https://openalex.org/A5107346850...,"[{'institution': {'country_code': 'DE', 'displ...","[{'country_code': 'BE', 'display_name': 'UCLou...","[{'count': 683, 'display_name': 'Astrophysics ...","[{'display_name': 'Neutrino Physics Research',...","[{'display_name': 'Physics', 'id': '121332964'...","[{'cited_by_count': 0, 'oa_works_count': 0, 'w...","Cantu, D. Rysewyk","{'first': 'd', 'last': 'cantu', 'middle': 'rys...",d cantu,https://api.openalex.org/works?filter=author.i...,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03
196,https://openalex.org/A5072713248,https://orcid.org/0000-0002-8154-6958,D. R. Napoli,"[A. Dewald, A. Gadea, D Napoli, D R Napoli, D ...",809,11474,"{'2yr_mean_citedness': 0.64, 'h_index': 46, 'i...",{'openalex': 'https://openalex.org/A5072713248...,"[{'institution': {'country_code': 'IT', 'displ...","[{'country_code': 'IT', 'display_name': 'Istit...","[{'count': 661, 'display_name': 'Nuclear physi...",[{'display_name': 'Astronomical and nuclear sc...,"[{'display_name': 'Physics', 'id': '121332964'...","[{'cited_by_count': 13, 'oa_works_count': 0, '...",D R Napoli for the Clara-Prisma collaboration,"{'first': 'd', 'last': 'collaboration', 'middl...",d collaboration,https://api.openalex.org/works?filter=author.i...,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03
197,https://openalex.org/A5076510192,https://orcid.org/0000-0003-0991-4434,Anthony Herrel,"[A HERREL, A Herrel, A. HERREL, A. Herrel, A. ...",808,23232,"{'2yr_mean_citedness': 1.8194444444444444, 'h_...",{'openalex': 'https://openalex.org/A5076510192...,"[{'institution': {'country_code': 'FR', 'displ...","[{'country_code': 'BE', 'display_name': 'Unive...","[{'count': 376, 'display_name': 'Amphibian and...",[{'display_name': 'Amphibian and Reptile Biolo...,"[{'display_name': 'Biology', 'id': '86803240',...","[{'cited_by_count': 177, 'oa_works_count': 0, ...","Anthony, Herrel","{'first': 'herrel', 'last': 'anthony', 'middle...",h anthony,https://api.openalex.org/works?filter=author.i...,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03
198,https://openalex.org/A5005945570,https://orcid.org/0000-0003-2711-8458,Teófilo Rojo,"[Adolfo La Rosa-Toro, Armand, M., J. I. Ruiz D...",806,39733,"{'2yr_mean_citedness': 9.333333333333334, 'h_i...",{'openalex': 'https://openalex.org/A5005945570...,"[{'institution': {'country_code': 'ES', 'displ...","[{'country_code': 'ES', 'display_name': 'Unive...","[{'count': 240, 'display_name': 'Advancements ...",[{'display_name': 'Crystal Structures and Prop...,"[{'display_name': 'Chemistry', 'id': '18559268...","[{'cited_by_count': 47, 'oa_works_count': 0, '...",J. I. Ruiz De Larramendi,"{'first': 'j', 'last': 'de larramendi', 'middl...",j de larramendi,https://api.openalex.org/works?filter=author.i...,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03
199,https://openalex.org/A5012273051,None,Francesc Illas,"[F ILLAS, F Illas, F. ILLAS, F. Illas, FRANCES...",805,36063,"{'2yr_mean_citedness': 10.0, 'h_index': 91, 'i...",{'openalex': 'https://openalex.org/A5012273051...,"[{'institution': {'country_code': 'EC', 'displ...","[{'country_code': 'ES', 'display_name': 'Unive...","[{'count': 297, 'display_name': 'Advanced Chem...",[{'display_name': 'Advanced Chemical Physics S...,"[{'display_name': 'Chemistry', 'id': '18559268...","[{'cited_by_count': 20, 'oa_works_count': 0, '...","Illas, Francesc","{'first': 'francesc', 'last': 'illas', 'middle...",f illas,https://api.openalex.org/works?filter=author.i...,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03

# Nodo

In [5]:
def openalex_load_author(df: pd.DataFrame)-> pd.DataFrame:
    
    df_author = df.drop(
        columns=[
            'display_name_alternatives', 
            'summary_stats', 
            'ids', 
            'affiliations', 
            'last_known_institutions', 
            'topics', 
            'topic_share', 
            'x_concepts', 
            'counts_by_year', 
            'works_api_url'
        ]
    )

    df_author = _add_openalex_extracted_metadata(df_author)
    df_author = df_author.convert_dtypes()
    df_author = _add_openalex_loaded_metadata(df_author)
    
    return df_author

# Ejecuto nodo

In [6]:
df_author = openalex_load_author(df_author_raw)

# Resultados

In [7]:
df_author

,id,orcid,display_name,works_count,cited_by_count,longest_name,parsed_longest_name,block_key,updated_date,created_date,_filter_param,_filter_value,_extract_datetime,_load_datetime
0,https://openalex.org/A5100630207,https://orcid.org/0000-0002-2770-9031,M. Weber,3820,258783,A. Washbrook,"{'first': 'a', 'last': 'washbrook', 'middle': ...",a washbrook,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03,2026-03-04 12:34:30.188816
1,https://openalex.org/A5006906048,https://orcid.org/0000-0002-5211-2536,Stefan R. Bornstein,3157,73662,Folkert W. Asselbergs,"{'first': 'folkert', 'last': 'asselbergs', 'mi...",f asselbergs,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03,2026-03-04 12:34:30.188816
2,https://openalex.org/A5061649047,https://orcid.org/0000-0002-2696-7266,Klaus A. Miczek,3088,23212,Klaus A. Miczek,"{'first': 'klaus', 'last': 'miczek', 'middle':...",k miczek,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03,2026-03-04 12:34:30.188816
3,https://openalex.org/A5087325828,<NA>,F. Barreiro,2901,182926,"Assamagan, Ketevi Adikle","{'first': 'ketevi', 'last': 'assamagan', 'midd...",k assamagan,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03,2026-03-04 12:34:30.188816
4,https://openalex.org/A5107465601,https://orcid.org/0000-0001-9500-2487,B. Trocmé,2808,190253,"Aaltonen, T.","{'first': 't', 'last': 'aaltonen', 'middle': '...",t aaltonen,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03,2026-03-04 12:34:30.188816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,https://openalex.org/A5107346850,https://orcid.org/0000-0002-2637-4778,H. Schieler,810,16272,"Cantu, D. Rysewyk","{'first': 'd', 'last': 'cantu', 'middle': 'rys...",d cantu,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03,2026-03-04 12:34:30.188816
196,https://openalex.org/A5072713248,https://orcid.org/0000-0002-8154-6958,D. R. Napoli,809,11474,D R Napoli for the Clara-Prisma collaboration,"{'first': 'd', 'last': 'collaboration', 'middl...",d collaboration,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03,2026-03-04 12:34:30.188816
197,https://openalex.org/A5076510192,https://orcid.org/0000-0003-0991-4434,Anthony Herrel,808,23232,"Anthony, Herrel","{'first': 'herrel', 'last': 'anthony', 'middle...",h anthony,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03,2026-03-04 12:34:30.188816
198,https://openalex.org/A5005945570,https://orcid.org/0000-0003-2711-8458,Teófilo Rojo,806,39733,J. I. Ruiz De Larramendi,"{'first': 'j', 'last': 'de larramendi', 'middl...",j de larramendi,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03,2026-03-04 12:34:30.188816
199,https://openalex.org/A5012273051,<NA>,Francesc Illas,805,36063,"Illas, Francesc","{'first': 'francesc', 'last': 'illas', 'middle...",f illas,2026-03-02T21:45:40,2016-06-24T00:00:00,affiliations.institution.ror,https://ror.org/03cqe8w59,2026-03-03,2026-03-04 12:34:30.188816