# VOC Sedici load

Notebook de prueba para el nodo `load_vocsedici_tables` del pipeline `load_vocsedici`.

Lee snapshots desde `raw/voc/{table}#parquet`, normaliza metadata de extraccion, agrega `_load_datetime` y deja los DataFrames listos para cargar en `ldg/vocsedici/{table}`. Esta notebook no hace `catalog.save`.

In [1]:
%load_ext kedro.ipython

The kedro.ipython extension is already loaded. To reload it, use:
  %reload_ext kedro.ipython

In [2]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 10)

In [3]:
tables = catalog.load("params:load_vocsedici_options.tables")
dataframes = [catalog.load(f"raw/voc/{table}#parquet") for table in tables]

[(table, df.shape) for table, df in zip(tables, dataframes)]

[06/19/26 14:22:53] INFO     Loading data from params:load_vocsedici_options.tables            ]8;id=918593;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=235234;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (MemoryDataset)...

[06/19/26 14:22:54] INFO     Loading data from raw/voc/node#parquet (ParquetDataset)...        ]8;id=284507;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=721376;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from raw/voc/node_field_data#parquet                 ]8;id=817535;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=762864;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/voc/paragraphs_item#parquet                 ]8;id=689738;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=662722;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/voc/paragraphs_item_field_data#parquet      ]8;id=721572;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=5843;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/voc/paragraph__field_persona_id#parquet     ]8;id=683687;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=888374;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/voc/paragraph__field_institucion#parquet    ]8;id=880183;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=243441;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/voc/paragraph__field_fecha_inicio#parquet   ]8;id=321207;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=201775;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/voc/paragraph__field_fecha_fin#parquet      ]8;id=806669;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=230247;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/voc/node__field_nombre#parquet              ]8;id=86820;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=626354;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/voc/node__field_apellido#parquet            ]8;id=527432;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=127374;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/voc/node__field_orcid#parquet               ]8;id=820163;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=276812;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/voc/node__field_mail#parquet                ]8;id=582953;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=619429;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/voc/node__field_dni#parquet                 ]8;id=339558;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=969120;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/voc/node__field_cuit#parquet                ]8;id=838887;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=343554;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/voc/node__field_telefono#parquet            ]8;id=252584;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=715001;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/voc/node__field_direcci_n#parquet           ]8;id=91943;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=554719;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/voc/node__field_google_scholar#parquet      ]8;id=582610;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=149638;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/voc/node__field_researchgate#parquet        ]8;id=835738;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=80224;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/voc/node__field_old_id#parquet              ]8;id=590505;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=863208;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/voc/node__field_filiacion#parquet           ]8;id=324435;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=147658;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/voc/node__field_nombre_institucion#parquet  ]8;id=101441;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=234146;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from                                                 ]8;id=843398;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=81734;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             raw/voc/node__field_nombre_institucion_variant#parquet
                             (ParquetDataset)...

                    INFO     Loading data from raw/voc/node__field_abreviatura#parquet         ]8;id=146864;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=147016;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/voc/node__field_id_pidu#parquet             ]8;id=791859;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=519711;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/voc/node__field_id_termino#parquet          ]8;id=978949;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=437799;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/voc/node__field_padre#parquet               ]8;id=814490;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=713739;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

[
    ('node', (37019, 13)),
    ('node_field_data', (37019, 21)),
    ('paragraphs_item', (39336, 13)),
    ('paragraphs_item_field_data', (39336, 20)),
    ('paragraph__field_persona_id', (26726, 15)),
    ('paragraph__field_institucion', (38559, 15)),
    ('paragraph__field_fecha_inicio', (185, 15)),
    ('paragraph__field_fecha_fin', (102, 15)),
    ('node__field_nombre', (36684, 15)),
    ('node__field_apellido', (36684, 15)),
    ('node__field_orcid', (2143, 15)),
    ('node__field_mail', (24606, 15)),
    ('node__field_dni', (3126, 15)),
    ('node__field_cuit', (16, 15)),
    ('node__field_telefono', (1, 15)),
    ('node__field_direcci_n', (1, 15)),
    ('node__field_google_scholar', (1363, 15)),
    ('node__field_researchgate', (385, 15)),
    ('node__field_old_id', (19012, 15)),
    ('node__field_filiacion', (38970, 16)),
    ('node__field_nombre_institucion', (335, 15)),
    ('node__field_nombre_institucion_variant', (3, 15)),
    ('node__field_abreviatura', (264, 15)),
    ('node__field_id_pidu', (161, 15)),
    ('node__field_id_termino', (134, 15)),
    ('node__field_padre', (254, 15))
]

## Funcion completa

Esta celda replica la implementacion del nodo `load_vocsedici_tables`. La idea es editar aca primero y despues copiar a `src/kedro_cic/pipelines/load_vocsedici/nodes.py`.

In [4]:
_EXTRACT_META_COLS = [
    "_source_system",
    "_source_table",
    "_extract_datetime",
    "_extract_date",
    "_source_label",
    "_extract_env",
    "_filter_param",
    "_filter_value",
]


def _add_extract_metadata(df: pd.DataFrame) -> pd.DataFrame:
    enriched_df = df.copy()
    for col in _EXTRACT_META_COLS:
        if col not in enriched_df.columns:
            enriched_df[col] = pd.NA
    enriched_df["_extract_datetime"] = pd.to_datetime(
        enriched_df["_extract_datetime"], errors="coerce"
    )
    if "_extract_date" in enriched_df.columns:
        enriched_df["_extract_date"] = pd.to_datetime(
            enriched_df["_extract_date"], errors="coerce"
        ).dt.date
    return enriched_df


def _add_load_metadata(df: pd.DataFrame, load_datetime=None) -> pd.DataFrame:
    enriched_df = df.copy()
    if load_datetime is None:
        load_datetime = pd.Timestamp.now(tz="UTC").floor("s").tz_localize(None)
    enriched_df["_load_datetime"] = pd.to_datetime(load_datetime)
    return enriched_df


def _prepare_table(df: pd.DataFrame) -> pd.DataFrame:
    prepared_df = _add_extract_metadata(df).convert_dtypes()
    return _add_load_metadata(prepared_df)


def load_vocsedici_tables(*dataframes):
    return tuple(_prepare_table(df) for df in dataframes)

In [5]:
loaded_tables = load_vocsedici_tables(*dataframes)

summary = pd.DataFrame(
    {
        "table": tables,
        "rows": [len(df) for df in loaded_tables],
        "columns": [len(df.columns) for df in loaded_tables],
        "source_system": [df["_source_system"].iloc[0] if len(df) else "voc" for df in loaded_tables],
        "source_label": [df["_source_label"].iloc[0] if len(df) else pd.NA for df in loaded_tables],
        "extract_datetime": [df["_extract_datetime"].iloc[0] if len(df) else pd.NA for df in loaded_tables],
        "load_datetime": [df["_load_datetime"].iloc[0] if len(df) else pd.NA for df in loaded_tables],
    }
)

summary

,table,rows,columns,source_system,source_label,extract_datetime,load_datetime
0,node,37019,14,voc,voc_sedici,2026-05-11 17:51:27,2026-06-19 17:22:55
1,node_field_data,37019,22,voc,voc_sedici,2026-05-11 17:51:27,2026-06-19 17:22:55
2,paragraphs_item,39336,14,voc,voc_sedici,2026-05-11 17:51:27,2026-06-19 17:22:55
3,paragraphs_item_field_data,39336,21,voc,voc_sedici,2026-05-11 17:51:27,2026-06-19 17:22:55
4,paragraph__field_persona_id,26726,16,voc,voc_sedici,2026-05-11 17:51:27,2026-06-19 17:22:55
...,...,...,...,...,...,...,...
21,node__field_nombre_institucion_variant,3,16,voc,voc_sedici,2026-05-11 17:51:27,2026-06-19 17:22:56
22,node__field_abreviatura,264,16,voc,voc_sedici,2026-05-11 17:51:27,2026-06-19 17:22:56
23,node__field_id_pidu,161,16,voc,voc_sedici,2026-05-11 17:51:27,2026-06-19 17:22:56
24,node__field_id_termino,134,16,voc,voc_sedici,2026-05-11 17:51:27,2026-06-19 17:22:56
25,node__field_padre,254,16,voc,voc_sedici,2026-05-11 17:51:27,2026-06-19 17:22:56

## Inspeccion rapida

Usar `table_to_preview` para revisar una tabla puntual antes de copiar cambios a `nodes.py`.

In [6]:
table_to_preview = "node"
df_preview = loaded_tables[tables.index(table_to_preview)]

df_preview.head()

,nid,vid,type,uuid,langcode,_source_system,_source_table,_extract_datetime,_extract_date,_source_label,_extract_env,_filter_param,_filter_value,_load_datetime
0,47001,19171,instituci_n,51bfd4f0-8571-4115-883a-5bbb39a2c106,es,voc,node,2026-05-11 17:51:27,2026-05-11,voc_sedici,dev,None,None,2026-06-19 17:22:55
1,47002,19172,instituci_n,98ff2bcd-ef94-41e3-a610-b1777b851214,es,voc,node,2026-05-11 17:51:27,2026-05-11,voc_sedici,dev,None,None,2026-06-19 17:22:55
2,47003,19173,instituci_n,14932fd7-2d42-4414-9050-d67c5e555c6c,es,voc,node,2026-05-11 17:51:27,2026-05-11,voc_sedici,dev,None,None,2026-06-19 17:22:55
3,47004,19174,instituci_n,acf5b60a-848d-469f-af01-cbbb6d73deb6,es,voc,node,2026-05-11 17:51:27,2026-05-11,voc_sedici,dev,None,None,2026-06-19 17:22:55
4,47005,28232,instituci_n,5676ac2d-5c27-45db-8cdf-3ea2f9f4b205,es,voc,node,2026-05-11 17:51:27,2026-05-11,voc_sedici,dev,None,None,2026-06-19 17:22:55

In [7]:
metadata_columns = [
    "_source_system",
    "_source_table",
    "_extract_datetime",
    "_extract_date",
    "_source_label",
    "_extract_env",
    "_filter_param",
    "_filter_value",
    "_load_datetime",
]

df_preview[metadata_columns].head()

,_source_system,_source_table,_extract_datetime,_extract_date,_source_label,_extract_env,_filter_param,_filter_value,_load_datetime
0,voc,node,2026-05-11 17:51:27,2026-05-11,voc_sedici,dev,None,None,2026-06-19 17:22:55
1,voc,node,2026-05-11 17:51:27,2026-05-11,voc_sedici,dev,None,None,2026-06-19 17:22:55
2,voc,node,2026-05-11 17:51:27,2026-05-11,voc_sedici,dev,None,None,2026-06-19 17:22:55
3,voc,node,2026-05-11 17:51:27,2026-05-11,voc_sedici,dev,None,None,2026-06-19 17:22:55
4,voc,node,2026-05-11 17:51:27,2026-05-11,voc_sedici,dev,None,None,2026-06-19 17:22:55