# dspace5_load

Esta notebook replica el nodo `load_dspace5`.
La idea es poder iterar acá, probar cambios sobre DataFrames reales y después copiar la función a `nodes.py`.

In [2]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 5)

df_bitstream = catalog.load('raw/dspace5/bitstream#parquet')
df_bundle2bitstream = catalog.load('raw/dspace5/bundle2bitstream#parquet')
df_collection2item = catalog.load('raw/dspace5/collection2item#parquet')
df_collection = catalog.load('raw/dspace5/collection#parquet')
df_community2collection = catalog.load('raw/dspace5/community2collection#parquet')
df_community2community = catalog.load('raw/dspace5/community2community#parquet')
df_community = catalog.load('raw/dspace5/community#parquet')
df_handle = catalog.load('raw/dspace5/handle#parquet')
df_item2bundle = catalog.load('raw/dspace5/item2bundle#parquet')
df_item = catalog.load('raw/dspace5/item#parquet')
df_metadatafieldregistry = catalog.load('raw/dspace5/metadatafieldregistry#parquet')
df_metadataschemaregistry = catalog.load('raw/dspace5/metadataschemaregistry#parquet')
df_metadatavalue = catalog.load('raw/dspace5/metadatavalue#parquet')

[03/26/26 09:28:03] INFO     Loading data from raw/dspace5/bitstream#parquet                   ]8;id=25143;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=361256;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

[03/26/26 09:28:05] INFO     Loading data from raw/dspace5/bundle2bitstream#parquet            ]8;id=529308;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=37543;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/dspace5/collection2item#parquet             ]8;id=969651;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=65444;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/dspace5/collection#parquet                  ]8;id=952805;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=742854;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/dspace5/community2collection#parquet        ]8;id=944772;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=262474;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/dspace5/community2community#parquet         ]8;id=511680;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=14614;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/dspace5/community#parquet                   ]8;id=408964;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=748177;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

[03/26/26 09:28:06] INFO     Loading data from raw/dspace5/handle#parquet (ParquetDataset)...  ]8;id=582106;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=716968;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from raw/dspace5/item2bundle#parquet                 ]8;id=242035;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=343622;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/dspace5/item#parquet (ParquetDataset)...    ]8;id=788763;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=678545;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from raw/dspace5/metadatafieldregistry#parquet       ]8;id=507249;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=656602;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/dspace5/metadataschemaregistry#parquet      ]8;id=394152;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=419606;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

                    INFO     Loading data from raw/dspace5/metadatavalue#parquet               ]8;id=864627;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=665896;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (ParquetDataset)...

## Función completa

Esta celda replica la implementación del nodo. La idea es editar acá primero y después copiar a `src/kedro_cic/pipelines/dspace5_load/nodes.py`.

In [3]:
_EXTRACT_META_COLS = ['_source_label', '_institution_ror', '_extract_datetime']


def _add_extract_metadata(df: pd.DataFrame) -> pd.DataFrame:
    enriched_df = df.copy()
    for col in _EXTRACT_META_COLS:
        if col not in enriched_df.columns:
            enriched_df[col] = pd.NA
    enriched_df['_extract_datetime'] = pd.to_datetime(
        enriched_df['_extract_datetime'], errors='coerce'
    )
    return enriched_df


def _add_load_metadata(df: pd.DataFrame, load_datetime=None) -> pd.DataFrame:
    enriched_df = df.copy()
    if load_datetime is None:
        load_datetime = pd.Timestamp.now(tz='UTC').floor('s').tz_localize(None)
    enriched_df['_load_datetime'] = pd.to_datetime(load_datetime)
    return enriched_df


def _astype_str(df: pd.DataFrame, columns: list[str]) -> pd.DataFrame:
    for column in columns:
        if column in df.columns:
            df[column] = df[column].astype(str)
    return df


def _prepare_table(
    df: pd.DataFrame,
    string_columns: list[str] | None = None,
    drop_columns: list[str] | None = None,
) -> pd.DataFrame:
    prepared_df = _add_extract_metadata(df).convert_dtypes()
    if string_columns:
        prepared_df = _astype_str(prepared_df, string_columns)
    if drop_columns:
        prepared_df = prepared_df.drop(columns=drop_columns, errors='ignore')
    return _add_load_metadata(prepared_df)


def load_dspace5(
    df_bitstream,
    df_bundle2bitstream,
    df_collection2item,
    df_collection,
    df_community2collection,
    df_community2community,
    df_community,
    df_handle,
    df_item2bundle,
    df_item,
    df_metadatafieldregistry,
    df_metadataschemaregistry,
    df_metadatavalue,
):
    return (
        _prepare_table(df_bitstream, string_columns=['uuid']),
        _prepare_table(
            df_bundle2bitstream, string_columns=['bundle_id', 'bitstream_id']
        ),
        _prepare_table(df_collection2item, string_columns=['collection_id', 'item_id']),
        _prepare_table(
            df_collection,
            string_columns=['uuid', 'submitter', 'admin'],
            drop_columns=['template_item_id', 'logo_bitstream_id'],
        ),
        _prepare_table(
            df_community2collection,
            string_columns=['collection_id', 'community_id'],
        ),
        _prepare_table(
            df_community2community,
            string_columns=['parent_comm_id', 'child_comm_id'],
        ),
        _prepare_table(
            df_community,
            string_columns=['uuid', 'admin'],
            drop_columns=['logo_bitstream_id'],
        ),
        _prepare_table(df_handle, string_columns=['resource_id']),
        _prepare_table(df_item2bundle, string_columns=['bundle_id', 'item_id']),
        _prepare_table(
            df_item,
            string_columns=['uuid', 'item_id', 'submitter_id', 'owning_collection'],
        ),
        _prepare_table(df_metadatafieldregistry),
        _prepare_table(df_metadataschemaregistry),
        _prepare_table(df_metadatavalue, string_columns=['dspace_object_id']),
    )

## Ejecución de prueba

Acá podés ejecutar la función completa y revisar algunas salidas antes de mover cambios al nodo real.

In [4]:
(
    df_bitstream_ldg,
    df_bundle2bitstream_ldg,
    df_collection2item_ldg,
    df_collection_ldg,
    df_community2collection_ldg,
    df_community2community_ldg,
    df_community_ldg,
    df_handle_ldg,
    df_item2bundle_ldg,
    df_item_ldg,
    df_metadatafieldregistry_ldg,
    df_metadataschemaregistry_ldg,
    df_metadatavalue_ldg,
) = load_dspace5(
    df_bitstream,
    df_bundle2bitstream,
    df_collection2item,
    df_collection,
    df_community2collection,
    df_community2community,
    df_community,
    df_handle,
    df_item2bundle,
    df_item,
    df_metadatafieldregistry,
    df_metadataschemaregistry,
    df_metadatavalue,
)

In [5]:
df_item_ldg.head()

,item_id,submitter_id,in_archive,withdrawn,last_modified,owning_collection,discoverable,_source_label,_institution_ror,_extract_datetime,_load_datetime
0,184986,14433,True,False,2024-08-21 20:02:17.638000+00:00,5547,True,sedici,https://ror.org/01tjs6929,2026-03-26 12:03:31,2026-03-26 12:32:24
1,29204,1178,True,False,2024-04-12 17:44:01.006000+00:00,1527,True,sedici,https://ror.org/01tjs6929,2026-03-26 12:03:31,2026-03-26 12:32:24
2,29223,1178,True,False,2024-04-12 17:45:34.504000+00:00,1527,True,sedici,https://ror.org/01tjs6929,2026-03-26 12:03:31,2026-03-26 12:32:24
3,30273,7318,True,False,2024-04-12 17:30:02.891000+00:00,1564,True,sedici,https://ror.org/01tjs6929,2026-03-26 12:03:31,2026-03-26 12:32:24
4,30274,7318,True,False,2024-04-12 17:41:21.307000+00:00,1564,True,sedici,https://ror.org/01tjs6929,2026-03-26 12:03:31,2026-03-26 12:32:24

In [6]:
df_collection_ldg.head()

,collection_id,workflow_step_1,workflow_step_2,workflow_step_3,submitter,admin,_source_label,_institution_ror,_extract_datetime,_load_datetime
0,1,None,None,None,<NA>,<NA>,sedici,https://ror.org/01tjs6929,2026-03-26 12:03:31,2026-03-26 12:32:22
1,2,None,None,None,<NA>,<NA>,sedici,https://ror.org/01tjs6929,2026-03-26 12:03:31,2026-03-26 12:32:22
2,3,None,None,None,<NA>,<NA>,sedici,https://ror.org/01tjs6929,2026-03-26 12:03:31,2026-03-26 12:32:22
3,4,None,None,None,<NA>,<NA>,sedici,https://ror.org/01tjs6929,2026-03-26 12:03:31,2026-03-26 12:32:22
4,1326,None,None,None,<NA>,<NA>,sedici,https://ror.org/01tjs6929,2026-03-26 12:03:31,2026-03-26 12:32:22

In [7]:
df_metadatavalue_ldg.head()

,metadata_value_id,resource_id,metadata_field_id,text_value,text_lang,place,authority,confidence,resource_type_id,_source_label,_institution_ror,_extract_datetime,_load_datetime
0,10822487,571963,55,Written by FormatFilter org.dspace.app.mediafi...,<NA>,1,<NA>,-1,0,sedici,https://ror.org/01tjs6929,2026-03-26 12:03:31,2026-03-26 12:32:34
1,10822488,571963,26,Extracted text,<NA>,1,<NA>,-1,0,sedici,https://ror.org/01tjs6929,2026-03-26 12:03:31,2026-03-26 12:32:34
2,10822489,521983,64,TEXT,<NA>,1,<NA>,-1,1,sedici,https://ror.org/01tjs6929,2026-03-26 12:03:31,2026-03-26 12:32:34
3,10822490,571964,64,Análisis_de_Art_15_2°_párrafo_de_ley_24241-PDF...,<NA>,1,<NA>,-1,0,sedici,https://ror.org/01tjs6929,2026-03-26 12:03:31,2026-03-26 12:32:34
4,10822491,571964,55,Written by FormatFilter org.dspace.app.mediafi...,<NA>,1,<NA>,-1,0,sedici,https://ror.org/01tjs6929,2026-03-26 12:03:31,2026-03-26 12:32:34