# VOC Sedici Extract Tables

Notebook de trabajo para replicar el comportamiento actual de `vocsedici_extract_tables` y revisar los dataframes resultantes.

In [1]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

## Setup

In [2]:
tables = catalog.load("params:vocsedici_extract_options.tables")
source_label = catalog.load("params:vocsedici_extract_options.source_label")
env = catalog.load("params:vocsedici_extract_options.env")
filter_param = catalog.load("params:vocsedici_extract_options.filter_param")
filter_value = catalog.load("params:vocsedici_extract_options.filter_value")

df_node = catalog.load("voc_mariadb/node")
df_node_field_data = catalog.load("voc_mariadb/node_field_data")
df_field_nombre = catalog.load("voc_mariadb/node__field_nombre")
df_field_apellido = catalog.load("voc_mariadb/node__field_apellido")
df_field_orcid = catalog.load("voc_mariadb/node__field_orcid")
df_field_mail = catalog.load("voc_mariadb/node__field_mail")
df_field_dni = catalog.load("voc_mariadb/node__field_dni")
df_field_cuit = catalog.load("voc_mariadb/node__field_cuit")
df_field_telefono = catalog.load("voc_mariadb/node__field_telefono")
df_field_direccion = catalog.load("voc_mariadb/node__field_direcci_n")
df_field_google_scholar = catalog.load("voc_mariadb/node__field_google_scholar")
df_field_researchgate = catalog.load("voc_mariadb/node__field_researchgate")
df_field_old_id = catalog.load("voc_mariadb/node__field_old_id")
df_field_filiacion = catalog.load("voc_mariadb/node__field_filiacion")
df_field_nombre_institucion = catalog.load("voc_mariadb/node__field_nombre_institucion")
df_field_nombre_institucion_variant = catalog.load("voc_mariadb/node__field_nombre_institucion_variant")
df_field_abreviatura = catalog.load("voc_mariadb/node__field_abreviatura")
df_field_id_pidu = catalog.load("voc_mariadb/node__field_id_pidu")
df_field_id_termino = catalog.load("voc_mariadb/node__field_id_termino")
df_field_padre = catalog.load("voc_mariadb/node__field_padre")

print(f"source_label={source_label}")
print(f"env={env}")
print(f"filter_param={filter_param}")
print(f"filter_value={filter_value}")
print(f"tables={len(tables)}")

                    INFO     Loading data from params:vocsedici_extract_options.tables         ]8;id=811268;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=305379;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (MemoryDataset)...

                    INFO     Loading data from params:vocsedici_extract_options.source_label   ]8;id=969008;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=404813;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (MemoryDataset)...

                    INFO     Loading data from params:vocsedici_extract_options.env            ]8;id=350880;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=783327;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (MemoryDataset)...

                    INFO     Loading data from params:vocsedici_extract_options.filter_param   ]8;id=312140;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=921200;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (MemoryDataset)...

                    INFO     Loading data from params:vocsedici_extract_options.filter_value   ]8;id=189086;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=300003;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (MemoryDataset)...

                    INFO     Loading data from voc_mariadb/node (SQLTableDataset)...           ]8;id=587494;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=580730;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

[05/11/26 12:55:42] INFO     Loading data from voc_mariadb/node_field_data                     ]8;id=361130;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=767453;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (SQLTableDataset)...

[05/11/26 12:55:43] INFO     Loading data from voc_mariadb/node__field_nombre                  ]8;id=192175;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=79518;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (SQLTableDataset)...

                    INFO     Loading data from voc_mariadb/node__field_apellido                ]8;id=859369;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=118357;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (SQLTableDataset)...

[05/11/26 12:55:44] INFO     Loading data from voc_mariadb/node__field_orcid                   ]8;id=190027;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=873187;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (SQLTableDataset)...

                    INFO     Loading data from voc_mariadb/node__field_mail                    ]8;id=768898;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=690650;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (SQLTableDataset)...

[05/11/26 12:55:45] INFO     Loading data from voc_mariadb/node__field_dni                     ]8;id=490985;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=643280;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (SQLTableDataset)...

                    INFO     Loading data from voc_mariadb/node__field_cuit                    ]8;id=78341;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=471564;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (SQLTableDataset)...

                    INFO     Loading data from voc_mariadb/node__field_telefono                ]8;id=525850;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=805009;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (SQLTableDataset)...

                    INFO     Loading data from voc_mariadb/node__field_direcci_n               ]8;id=163606;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=60471;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (SQLTableDataset)...

                    INFO     Loading data from voc_mariadb/node__field_google_scholar          ]8;id=666604;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=315438;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (SQLTableDataset)...

                    INFO     Loading data from voc_mariadb/node__field_researchgate            ]8;id=373775;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=94579;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (SQLTableDataset)...

                    INFO     Loading data from voc_mariadb/node__field_old_id                  ]8;id=671125;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=323058;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (SQLTableDataset)...

                    INFO     Loading data from voc_mariadb/node__field_filiacion               ]8;id=332949;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=966435;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (SQLTableDataset)...

[05/11/26 12:55:47] INFO     Loading data from voc_mariadb/node__field_nombre_institucion      ]8;id=482847;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=280188;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (SQLTableDataset)...

                    INFO     Loading data from                                                 ]8;id=341729;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=683938;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             voc_mariadb/node__field_nombre_institucion_variant
                             (SQLTableDataset)...

                    INFO     Loading data from voc_mariadb/node__field_abreviatura             ]8;id=879765;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=777122;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (SQLTableDataset)...

                    INFO     Loading data from voc_mariadb/node__field_id_pidu                 ]8;id=971401;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=578016;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (SQLTableDataset)...

                    INFO     Loading data from voc_mariadb/node__field_id_termino              ]8;id=895717;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=513120;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (SQLTableDataset)...

                    INFO     Loading data from voc_mariadb/node__field_padre                   ]8;id=690165;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=997041;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (SQLTableDataset)...

source_label=voc_sedici
env=dev
filter_param=
filter_value=None
tables=20

In [3]:
datasets = {
    "node": df_node,
    "node_field_data": df_node_field_data,
    "node__field_nombre": df_field_nombre,
    "node__field_apellido": df_field_apellido,
    "node__field_orcid": df_field_orcid,
    "node__field_mail": df_field_mail,
    "node__field_dni": df_field_dni,
    "node__field_cuit": df_field_cuit,
    "node__field_telefono": df_field_telefono,
    "node__field_direcci_n": df_field_direccion,
    "node__field_google_scholar": df_field_google_scholar,
    "node__field_researchgate": df_field_researchgate,
    "node__field_old_id": df_field_old_id,
    "node__field_filiacion": df_field_filiacion,
    "node__field_nombre_institucion": df_field_nombre_institucion,
    "node__field_nombre_institucion_variant": df_field_nombre_institucion_variant,
    "node__field_abreviatura": df_field_abreviatura,
    "node__field_id_pidu": df_field_id_pidu,
    "node__field_id_termino": df_field_id_termino,
    "node__field_padre": df_field_padre,
}

pd.Series({name: len(df) for name, df in datasets.items()}).sort_index()

node                                      37019
node__field_abreviatura                     264
node__field_apellido                      36684
node__field_cuit                             16
node__field_direcci_n                         1
node__field_dni                            3126
node__field_filiacion                     38970
node__field_google_scholar                 1363
node__field_id_pidu                         161
node__field_id_termino                      134
node__field_mail                          24606
node__field_nombre                        36684
node__field_nombre_institucion              335
node__field_nombre_institucion_variant        3
node__field_old_id                        19012
node__field_orcid                          2143
node__field_padre                           254
node__field_researchgate                    385
node__field_telefono                          1
node_field_data                           37019
dtype: int64

## Node Logic

In [4]:
VOCSEDICI_TABLES = (
    "node",
    "node_field_data",
    "node__field_nombre",
    "node__field_apellido",
    "node__field_orcid",
    "node__field_mail",
    "node__field_dni",
    "node__field_cuit",
    "node__field_telefono",
    "node__field_direcci_n",
    "node__field_google_scholar",
    "node__field_researchgate",
    "node__field_old_id",
    "node__field_filiacion",
    "node__field_nombre_institucion",
    "node__field_nombre_institucion_variant",
    "node__field_abreviatura",
    "node__field_id_pidu",
    "node__field_id_termino",
    "node__field_padre",
)


def _add_extract_metadata(
    df: pd.DataFrame,
    *,
    source_label: str,
    extract_env: str,
    source_table: str,
    filter_param: str | None,
    filter_value,
    extract_datetime: pd.Timestamp,
) -> pd.DataFrame:
    enriched_df = df.copy()
    enriched_df["_source_system"] = "voc"
    enriched_df["_source_table"] = source_table
    enriched_df["_extract_datetime"] = extract_datetime
    enriched_df["_extract_date"] = extract_datetime.date()
    enriched_df["_source_label"] = source_label
    enriched_df["_extract_env"] = extract_env
    enriched_df["_filter_param"] = filter_param if filter_param else pd.NA
    enriched_df["_filter_value"] = filter_value if filter_value not in (None, "") else pd.NA
    return enriched_df


def vocsedici_extract_tables(
    tables,
    source_label,
    extract_env,
    filter_param,
    filter_value,
    *dataframes,
):
    configured_tables = tuple(tables)

    if configured_tables != VOCSEDICI_TABLES:
        raise ValueError(
            f"Configured tables do not match pipeline inputs. Expected {VOCSEDICI_TABLES}, got {configured_tables}."
        )

    if len(dataframes) != len(VOCSEDICI_TABLES):
        raise ValueError(
            f"Expected {len(VOCSEDICI_TABLES)} dataframes, got {len(dataframes)}."
        )

    extract_datetime = pd.Timestamp.now(tz="UTC").floor("s").tz_localize(None)

    return tuple(
        _add_extract_metadata(
            df,
            source_label=source_label,
            extract_env=extract_env,
            source_table=table_name,
            filter_param=filter_param,
            filter_value=filter_value,
            extract_datetime=extract_datetime,
        )
        for table_name, df in zip(VOCSEDICI_TABLES, dataframes)
    )

## Run

In [5]:
extracted_tables = vocsedici_extract_tables(
    tables,
    source_label,
    env,
    filter_param,
    filter_value,
    df_node,
    df_node_field_data,
    df_field_nombre,
    df_field_apellido,
    df_field_orcid,
    df_field_mail,
    df_field_dni,
    df_field_cuit,
    df_field_telefono,
    df_field_direccion,
    df_field_google_scholar,
    df_field_researchgate,
    df_field_old_id,
    df_field_filiacion,
    df_field_nombre_institucion,
    df_field_nombre_institucion_variant,
    df_field_abreviatura,
    df_field_id_pidu,
    df_field_id_termino,
    df_field_padre,
)

len(extracted_tables)

20

In [6]:
for table_name, df in zip(VOCSEDICI_TABLES, extracted_tables):
    print(f"\\n=== {table_name} ===")
    print(f"rows={len(df):,} cols={len(df.columns)}")
    display(df.head(3))

\n=== node ===
rows=37,019 cols=13

     nid    vid         type                                  uuid langcode _source_system _source_table   _extract_datetime _extract_date _source_label _extract_env _filter_param _filter_value
0  47001  19171  instituci_n  51bfd4f0-8571-4115-883a-5bbb39a2c106       es            voc          node 2026-05-11 15:55:47    2026-05-11    voc_sedici          dev          <NA>          <NA>
1  47002  19172  instituci_n  98ff2bcd-ef94-41e3-a610-b1777b851214       es            voc          node 2026-05-11 15:55:47    2026-05-11    voc_sedici          dev          <NA>          <NA>
2  47003  19173  instituci_n  14932fd7-2d42-4414-9050-d67c5e555c6c       es            voc          node 2026-05-11 15:55:47    2026-05-11    voc_sedici          dev          <NA>          <NA>

\n=== node_field_data ===
rows=37,019 cols=21

,nid,vid,type,langcode,status,uid,title,created,changed,promote,sticky,default_langcode,revision_translation_affected,_source_system,_source_table,_extract_datetime,_extract_date,_source_label,_extract_env,_filter_param,_filter_value
0,47001,19171,instituci_n,es,1,0,Universidad Nacional de La Plata,1531930556,1565274611,1,0,1,1.0,voc,node_field_data,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
1,47002,19172,instituci_n,es,1,0,Comisión Nacional de Energía Atómica,1531930556,1565274611,1,0,1,1.0,voc,node_field_data,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
2,47003,19173,instituci_n,es,1,0,Colegio de Farmacéuticos de la Provincia de Bu...,1531930556,1565274611,1,0,1,1.0,voc,node_field_data,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>

\n=== node__field_nombre ===
rows=36,684 cols=15

,bundle,deleted,entity_id,revision_id,langcode,delta,field_nombre_value,_source_system,_source_table,_extract_datetime,_extract_date,_source_label,_extract_env,_filter_param,_filter_value
0,persona,0,48430,1,und,0,Alfredo Carlos,voc,node__field_nombre,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
1,persona,0,48431,2,es,0,Pablo David,voc,node__field_nombre,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
2,persona,0,48432,3,und,0,Carlos Luis,voc,node__field_nombre,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>

\n=== node__field_apellido ===
rows=36,684 cols=15

,bundle,deleted,entity_id,revision_id,langcode,delta,field_apellido_value,_source_system,_source_table,_extract_datetime,_extract_date,_source_label,_extract_env,_filter_param,_filter_value
0,persona,0,48430,1,und,0,González,voc,node__field_apellido,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
1,persona,0,48431,2,es,0,Bilmes,voc,node__field_apellido,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
2,persona,0,48432,3,und,0,Llorente,voc,node__field_apellido,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>

\n=== node__field_orcid ===
rows=2,143 cols=15

,bundle,deleted,entity_id,revision_id,langcode,delta,field_orcid_value,_source_system,_source_table,_extract_datetime,_extract_date,_source_label,_extract_env,_filter_param,_filter_value
0,persona,0,48448,19,und,0,0000-0001-6298-6483,voc,node__field_orcid,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
1,persona,0,48452,23,es,0,0000-0003-4442-0018,voc,node__field_orcid,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
2,persona,0,48463,34,und,0,0000-0001-5831-3737,voc,node__field_orcid,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>

\n=== node__field_mail ===
rows=24,606 cols=15

,bundle,deleted,entity_id,revision_id,langcode,delta,field_mail_value,_source_system,_source_table,_extract_datetime,_extract_date,_source_label,_extract_env,_filter_param,_filter_value
0,persona,0,48430,1,und,0,algonza@ing.unlp.edu.ar,voc,node__field_mail,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
1,persona,0,48432,3,und,0,cllorent@ing.unlp.edu.ar,voc,node__field_mail,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
2,persona,0,48434,5,und,0,adriana.barboza@ing.unlp.edu.ar,voc,node__field_mail,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>

\n=== node__field_dni ===
rows=3,126 cols=15

    bundle  deleted  entity_id  revision_id langcode  delta field_dni_value _source_system    _source_table   _extract_datetime _extract_date _source_label _extract_env _filter_param _filter_value
0  persona        0      48432            3      und      0       11421730             voc  node__field_dni 2026-05-11 15:55:47    2026-05-11    voc_sedici          dev          <NA>          <NA>
1  persona        0      48446           17       es      0        22029756            voc  node__field_dni 2026-05-11 15:55:47    2026-05-11    voc_sedici          dev          <NA>          <NA>
2  persona        0      48449           20      und      0       11616800             voc  node__field_dni 2026-05-11 15:55:47    2026-05-11    voc_sedici          dev          <NA>          <NA>

\n=== node__field_cuit ===
rows=16 cols=15

,bundle,deleted,entity_id,revision_id,langcode,delta,field_cuit_value,_source_system,_source_table,_extract_datetime,_extract_date,_source_label,_extract_env,_filter_param,_filter_value
0,persona,0,55609,7180,und,0,27-18435028-4,voc,node__field_cuit,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
1,persona,0,57269,8840,es,0,0009-0002-8813-7687,voc,node__field_cuit,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
2,persona,0,59598,11169,und,0,23-16397965-9,voc,node__field_cuit,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>

\n=== node__field_telefono ===
rows=1 cols=15

,bundle,deleted,entity_id,revision_id,langcode,delta,field_telefono_value,_source_system,_source_table,_extract_datetime,_extract_date,_source_label,_extract_env,_filter_param,_filter_value
0,instituci_n,0,77001,30083,es,0,+54 (0221) 4229923,voc,node__field_telefono,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>

\n=== node__field_direcci_n ===
rows=1 cols=15

,bundle,deleted,entity_id,revision_id,langcode,delta,field_direcci_n_value,_source_system,_source_table,_extract_datetime,_extract_date,_source_label,_extract_env,_filter_param,_filter_value
0,instituci_n,0,77001,30083,es,0,calle 3 N° 584 – La Plata (1900),voc,node__field_direcci_n,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>

\n=== node__field_google_scholar ===
rows=1,363 cols=15

,bundle,deleted,entity_id,revision_id,langcode,delta,field_google_scholar_value,_source_system,_source_table,_extract_datetime,_extract_date,_source_label,_extract_env,_filter_param,_filter_value
0,persona,0,48490,61,und,0,https://scholar.google.com.ar/citations?user=h...,voc,node__field_google_scholar,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
1,persona,0,48501,72,es,0,https://scholar.google.com.ar/citations?user=6...,voc,node__field_google_scholar,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
2,persona,0,48505,76,und,0,https://scholar.google.com/citations?user=nRfo...,voc,node__field_google_scholar,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>

\n=== node__field_researchgate ===
rows=385 cols=15

,bundle,deleted,entity_id,revision_id,langcode,delta,field_researchgate_value,_source_system,_source_table,_extract_datetime,_extract_date,_source_label,_extract_env,_filter_param,_filter_value
0,persona,0,48445,16,und,0,https://www.researchgate.net/profile/Danilo-Vu...,voc,node__field_researchgate,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
1,persona,0,48631,202,und,0,https://www.researchgate.net/profile/Mauricio_...,voc,node__field_researchgate,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
2,persona,0,48667,238,und,0,https://www.researchgate.net/profile/Ana_Dumrauf,voc,node__field_researchgate,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>

\n=== node__field_old_id ===
rows=19,012 cols=15

,bundle,deleted,entity_id,revision_id,langcode,delta,field_old_id_value,_source_system,_source_table,_extract_datetime,_extract_date,_source_label,_extract_env,_filter_param,_filter_value
0,persona,0,48430,1,und,0,12649,voc,node__field_old_id,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
1,persona,0,48431,2,es,0,12650,voc,node__field_old_id,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
2,persona,0,48432,3,und,0,12651,voc,node__field_old_id,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>

\n=== node__field_filiacion ===
rows=38,970 cols=16

,bundle,deleted,entity_id,revision_id,langcode,delta,field_filiacion_target_id,field_filiacion_target_revision_id,_source_system,_source_table,_extract_datetime,_extract_date,_source_label,_extract_env,_filter_param,_filter_value
0,persona,0,48430,1,und,0,1,1,voc,node__field_filiacion,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
1,persona,0,48430,1,und,1,10,10,voc,node__field_filiacion,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
2,persona,0,48431,2,es,0,2,2,voc,node__field_filiacion,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>

\n=== node__field_nombre_institucion ===
rows=335 cols=15

,bundle,deleted,entity_id,revision_id,langcode,delta,field_nombre_institucion_value,_source_system,_source_table,_extract_datetime,_extract_date,_source_label,_extract_env,_filter_param,_filter_value
0,instituci_n,0,47001,19171,es,0,Universidad Nacional de La Plata,voc,node__field_nombre_institucion,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
1,instituci_n,0,47002,19172,es,0,Comisión Nacional de Energía Atómica,voc,node__field_nombre_institucion,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
2,instituci_n,0,47003,19173,es,0,Colegio de Farmacéuticos de la Provincia de Bu...,voc,node__field_nombre_institucion,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>

\n=== node__field_nombre_institucion_variant ===
rows=3 cols=15

,bundle,deleted,entity_id,revision_id,langcode,delta,field_nombre_institucion_variant_value,_source_system,_source_table,_extract_datetime,_extract_date,_source_label,_extract_env,_filter_param,_filter_value
0,instituci_n,0,47690,19873,es,0,Facultad de Bellas Artes,voc,node__field_nombre_institucion_variant,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
1,instituci_n,0,69130,26426,es,0,Asociación Argentina de Energía Solar,voc,node__field_nombre_institucion_variant,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
2,instituci_n,0,72467,25500,es,0,Laboratorio de Virología (LAVIR),voc,node__field_nombre_institucion_variant,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>

\n=== node__field_abreviatura ===
rows=264 cols=15

,bundle,deleted,entity_id,revision_id,langcode,delta,field_abreviatura_value,_source_system,_source_table,_extract_datetime,_extract_date,_source_label,_extract_env,_filter_param,_filter_value
0,instituci_n,0,47001,19171,es,0,UNLP,voc,node__field_abreviatura,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
1,instituci_n,0,47002,19172,es,0,CNEA,voc,node__field_abreviatura,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
2,instituci_n,0,47003,19173,es,0,FARM,voc,node__field_abreviatura,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>

\n=== node__field_id_pidu ===
rows=161 cols=15

,bundle,deleted,entity_id,revision_id,langcode,delta,field_id_pidu_value,_source_system,_source_table,_extract_datetime,_extract_date,_source_label,_extract_env,_filter_param,_filter_value
0,instituci_n,0,47001,19171,es,0,1,voc,node__field_id_pidu,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
1,instituci_n,0,47002,19172,es,0,5,voc,node__field_id_pidu,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
2,instituci_n,0,47003,19173,es,0,53,voc,node__field_id_pidu,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>

\n=== node__field_id_termino ===
rows=134 cols=15

,bundle,deleted,entity_id,revision_id,langcode,delta,field_id_termino_value,_source_system,_source_table,_extract_datetime,_extract_date,_source_label,_extract_env,_filter_param,_filter_value
0,instituci_n,0,47001,19171,es,0,1.1,voc,node__field_id_termino,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
1,instituci_n,0,47002,19172,es,0,1.15,voc,node__field_id_termino,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
2,instituci_n,0,47003,19173,es,0,1.38,voc,node__field_id_termino,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>

\n=== node__field_padre ===
rows=254 cols=15

,bundle,deleted,entity_id,revision_id,langcode,delta,field_padre_target_id,_source_system,_source_table,_extract_datetime,_extract_date,_source_label,_extract_env,_filter_param,_filter_value
0,instituci_n,0,47685,19855,es,0,47001,voc,node__field_padre,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
1,instituci_n,0,47686,19863,es,0,47001,voc,node__field_padre,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>
2,instituci_n,0,47687,19870,es,0,47001,voc,node__field_padre,2026-05-11 15:55:47,2026-05-11,voc_sedici,dev,<NA>,<NA>