# dspacedb_extract

Esta notebook replica el nodo `extract_dspacedb`.
Lee tablas del esquema `dspace`, agrega metadata de institucion y fecha de extraccion, y deja snapshots en `raw/dspace/*#parquet`.

In [ ]:
import pandas as pd
from datetime import date

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 5)

source_label = catalog.load('params:dspace5_extract_options.source_label')
institution_ror = catalog.load('params:dspace5_extract_options.institution_ror')
tables = catalog.load("params:dspace5_extract_options.tables")

df_bitstream = catalog.load('dspace5/public/bitstream')
df_bundle = catalog.load('dspace5/public/bundle')
df_bundle2bitstream = catalog.load('dspace5/public/bundle2bitstream')
df_collection = catalog.load('dspace5/public/collection')
df_collection2item = catalog.load('dspace5/public/collection2item')
df_community = catalog.load('dspace5/public/community')
df_community2collection = catalog.load('dspace5/public/community2collection')
df_community2community = catalog.load('dspace5/public/community2community')
df_doi = catalog.load('dspace5/public/doi')
df_eperson = catalog.load('dspace5/public/eperson')
df_epersongroup = catalog.load('dspace5/public/epersongroup')
df_epersongroup2eperson = catalog.load('dspace5/public/epersongroup2eperson')
df_group2group = catalog.load('dspace5/public/group2group')
df_handle = catalog.load('dspace5/public/handle')
df_item = catalog.load('dspace5/public/item')
df_item2bundle = catalog.load('dspace5/public/item2bundle')
df_metadatafieldregistry = catalog.load('dspace5/public/metadatafieldregistry')
df_metadataschemaregistry = catalog.load('dspace5/public/metadataschemaregistry')
df_metadatavalue = catalog.load('dspace5/public/metadatavalue')

print(f'source_label: {source_label}')
print(f'institution_ror: {institution_ror}')

[03/26/26 08:55:15] INFO     Loading data from params:dspace5_extract_options.source_label     ]8;id=568977;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=919685;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (MemoryDataset)...

                    INFO     Loading data from params:dspace5_extract_options.institution_ror  ]8;id=959846;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=700258;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (MemoryDataset)...

                    INFO     Loading data from dspace5/public/bitstream (SQLTableDataset)...   ]8;id=845431;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=657725;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

[03/26/26 08:55:21] INFO     Loading data from dspace5/public/bundle (SQLTableDataset)...      ]8;id=871502;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=798643;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

[03/26/26 08:55:23] INFO     Loading data from dspace5/public/bundle2bitstream                 ]8;id=662726;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=775176;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (SQLTableDataset)...

[03/26/26 08:55:26] INFO     Loading data from dspace5/public/collection (SQLTableDataset)...  ]8;id=707776;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=998171;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from dspace5/public/collection2item                  ]8;id=203280;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=442656;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (SQLTableDataset)...

[03/26/26 08:55:27] INFO     Loading data from dspace5/public/community (SQLTableDataset)...   ]8;id=714160;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=721169;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from dspace5/public/community2collection             ]8;id=177079;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=676928;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (SQLTableDataset)...

[03/26/26 08:55:28] INFO     Loading data from dspace5/public/community2community              ]8;id=459640;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=952873;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (SQLTableDataset)...

                    INFO     Loading data from dspace5/public/doi (SQLTableDataset)...         ]8;id=969308;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=511115;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from dspace5/public/eperson (SQLTableDataset)...     ]8;id=985171;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=645192;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from dspace5/public/epersongroup                     ]8;id=170544;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=648940;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (SQLTableDataset)...

                    INFO     Loading data from dspace5/public/epersongroup2eperson             ]8;id=480477;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=777131;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (SQLTableDataset)...

                    INFO     Loading data from dspace5/public/group2group (SQLTableDataset)... ]8;id=730765;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=876709;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from dspace5/public/handle (SQLTableDataset)...      ]8;id=108046;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=850893;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

[03/26/26 08:55:29] INFO     Loading data from dspace5/public/item (SQLTableDataset)...        ]8;id=273001;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=294127;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

[03/26/26 08:55:31] INFO     Loading data from dspace5/public/item2bundle (SQLTableDataset)... ]8;id=325908;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=153187;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

[03/26/26 08:55:34] INFO     Loading data from dspace5/public/metadatafieldregistry            ]8;id=529123;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=475248;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (SQLTableDataset)...

                    INFO     Loading data from dspace5/public/metadataschemaregistry           ]8;id=969847;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=984301;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (SQLTableDataset)...

                    INFO     Loading data from dspace5/public/metadatavalue                    ]8;id=823073;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=514829;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\
                             (SQLTableDataset)...

source_label: sedici
institution_ror: https://ror.org/01tjs6929

## Metadata de extraccion

El pipeline agrega dos columnas a todas las tablas extraidas:

- `_institution_id`: identificador logico de la institucion.
- `_extract_datetime`: fecha del snapshot restaurado en el esquema `dspace`.

In [2]:
import pandas as pd


DSPACE5_TABLES = (
    "bitstream",
    "bundle2bitstream",
    "collection2item",
    "collection",
    "community2collection",
    "community2community",
    "community",
    "handle",
    "item2bundle",
    "item",
    "metadatafieldregistry",
    "metadataschemaregistry",
    "metadatavalue",
)


def _add_extract_metadata(
    df: pd.DataFrame,
    source_label: str,
    institution_ror: str,
    extract_datetime: pd.Timestamp,
) -> pd.DataFrame:
    df = df.copy()
    df["_source_label"] = source_label
    df["_institution_ror"] = institution_ror
    df["_extract_datetime"] = extract_datetime
    return df


def dspace5_extract_tables(
    tables,
    source_label,
    institution_ror,
    *dataframes,
):
    configured_tables = tuple(tables)

    if configured_tables != DSPACE5_TABLES:
        raise ValueError(
            f"Configured tables do not match pipeline inputs. "
            f"Expected {DSPACE5_TABLES}, got {configured_tables}."
        )

    if len(dataframes) != len(DSPACE5_TABLES):
        raise ValueError(
            f"Expected {len(DSPACE5_TABLES)} dataframes, got {len(dataframes)}."
        )

    extract_datetime = pd.Timestamp.now(tz="UTC").floor("s").tz_localize(None)

    return tuple(
        _add_extract_metadata(df, source_label, institution_ror, extract_datetime)
        for df in dataframes
    )

## Ejecucion sobre dos tablas de ejemplo

En la pipeline real se hace lo mismo para todas las tablas de DSpace. Aca se muestran `item` y `metadatavalue`, que suelen ser las mas utiles para inspeccionar el snapshot.

In [3]:
extracted_tables = dspace5_extract_tables(
    tables,
    source_label,
    institution_ror,
    df_bitstream,
    df_bundle2bitstream,
    df_collection2item,
    df_collection,
    df_community2collection,
    df_community2community,
    df_community,
    df_handle,
    df_item2bundle,
    df_item,
    df_metadatafieldregistry,
    df_metadataschemaregistry,
    df_metadatavalue,
)

In [4]:
df_item_extracted = extracted_tables[9]
df_item_extracted.head()

,item_id,submitter_id,in_archive,withdrawn,last_modified,owning_collection,discoverable,_source_label,_institution_ror,_extract_datetime
0,184986,14433.0,True,False,2024-08-21 20:02:17.638000+00:00,5547.0,True,sedici,https://ror.org/01tjs6929,2026-03-26 11:57:21
1,29204,1178.0,True,False,2024-04-12 17:44:01.006000+00:00,1527.0,True,sedici,https://ror.org/01tjs6929,2026-03-26 11:57:21
2,29223,1178.0,True,False,2024-04-12 17:45:34.504000+00:00,1527.0,True,sedici,https://ror.org/01tjs6929,2026-03-26 11:57:21
3,30273,7318.0,True,False,2024-04-12 17:30:02.891000+00:00,1564.0,True,sedici,https://ror.org/01tjs6929,2026-03-26 11:57:21
4,30274,7318.0,True,False,2024-04-12 17:41:21.307000+00:00,1564.0,True,sedici,https://ror.org/01tjs6929,2026-03-26 11:57:21

In [5]:
df_metadatavalue_extracted = extracted_tables[12]
df_metadatavalue_extracted.head()

,metadata_value_id,resource_id,metadata_field_id,text_value,text_lang,place,authority,confidence,resource_type_id,_source_label,_institution_ror,_extract_datetime
0,10822487,571963,55,Written by FormatFilter org.dspace.app.mediafi...,None,1.0,None,-1.0,0,sedici,https://ror.org/01tjs6929,2026-03-26 11:57:21
1,10822488,571963,26,Extracted text,None,1.0,None,-1.0,0,sedici,https://ror.org/01tjs6929,2026-03-26 11:57:21
2,10822489,521983,64,TEXT,None,1.0,None,-1.0,1,sedici,https://ror.org/01tjs6929,2026-03-26 11:57:21
3,10822490,571964,64,Análisis_de_Art_15_2°_párrafo_de_ley_24241-PDF...,None,1.0,None,-1.0,0,sedici,https://ror.org/01tjs6929,2026-03-26 11:57:21
4,10822491,571964,55,Written by FormatFilter org.dspace.app.mediafi...,None,1.0,None,-1.0,0,sedici,https://ror.org/01tjs6929,2026-03-26 11:57:21